### ISSUE TITLE
Polygon "authentication failed"

### ISSUE THREAD

**Issue by noterminusgit** [alphahub-us/xylem#1]
I'm getting an "authentication failed" message for Polygon when trying to use the client. I believe the issue is that the client uses Websockets, whish isn't an available feature on the free tier of Polygon's service. 

https://polygon.io/pricing

I don't have any log output, so here's some terminal output. I've removed the API key, but I've verified the key matches the one for my Polygon account.

```
root@localhost:~/xylem# iex -S mix
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit]

warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Compiling 25 files (.ex)
Generated xylem app
Interactive Elixir (1.12.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 22:06:29.677 [warn] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

22:06:30.832 [debug] listening for 'venue:my_venue' Alpaca account updates
22:06:32.189 [warn] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

22:06:32.189 [warn] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

22:06:32.376 [debug] listening for AlphaHub signals...
inbound message: [
  %{
    "ev" => "status",
    "message" => "authentication failed",
    "status" => "auth_failed"
  }
]
22:06:32.735 [error] GenServer {Xylem.Registry, "polygon", Xylem.Data.Polygon} terminating
** (FunctionClauseError) no function clause matching in Xylem.Data.Polygon.handle_receive/2
    (xylem 0.1.0) lib/xylem/data/polygon.ex:62: Xylem.Data.Polygon.handle_receive({:close, 1000, ""}, %{"key" => "<key>", "ready" => false})
    (xylem 0.1.0) lib/axil.ex:155: Xylem.Data.Polygon.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:gun_ws, #PID<0.451.0>, #Reference<0.3437225484.794558465.142869>, {:close, 1000, ""}}
State: {%Axil.Connection{client: #PID<0.451.0>, connect_opts: %{connect_timeout: 60000, protocols: [:http], retry: 5, retry_timeout: 5000}, host: 'socket.polygon.io', monitor: #Reference<0.3437225484.794558465.142868>, path: '/stocks', port: 443, stream: #Reference<0.3437225484.794558465.142869>, ws_opts: %{compress: false, protocols: []}}, %{"key" => "<key>", "ready" => false}}
22:06:32.757 [warn] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

inbound message: [
  %{
    "ev" => "status",
    "message" => "authentication failed",
    "status" => "auth_failed"
  }
]
22:06:33.144 [error] GenServer {Xylem.Registry, "polygon", Xylem.Data.Polygon} terminating
```

**Comment by dcrck** [comment]
Yep, that's correct. Those messages come from the WebSocket client. You'll need a Polygon plan with WebSockets access to use this solution as-is.

**Comment by noterminusgit** [comment]
That would put the cost to use this self-hosted FOSS solution at 5x the
cost of Arcade Trader, which is a SaaS solution? That doesn't make sense.

**Comment by dcrck** [comment]
I never made any claims that this was free. I published this code, which AlphaHub uses for its own trading, for transparency's sake. That is, to show that it isn't just buying the stock before everyone else. 

Additionally, this code provides another option showing how to build a trader to interact with AlphaHub's signals. Maybe you already have a paid Polygon subscription you're using for other things; maybe you want more control over your execution strategy than what ArcadeTrader provides. These are all just options with their own tradeoffs. If you don't want to buy a paid Polygon subscription, that's totally fine! That's why AlphaHub partnered with ArcadeTrader.

Hope this clears things up.

**Comment by noterminusgit** [comment]
None of those things, or the requirement for a premium Polygon account, were mentioned in the README.md. Had I known any of those things, I would have just opted for Arcade Trader.
